INSERT INTO TB_EMPLOYEE (ADMISSION_DATE, BIRTH_DATE, EMAIL, NAME, TOTAL_VACATION_DAYS) VALUES (NOW(), '2020-07-14T10:00:00Z', 'test@gmail.com', 'Marcelo Mariath', 12);
INSERT INTO TB_EMPLOYEE (ADMISSION_DATE, BIRTH_DATE, EMAIL, NAME, TOTAL_VACATION_DAYS) VALUES (NOW(), '2020-07-14T10:00:00Z', 'lucas@gmail.com', 'Lucas Schenck', 19);
INSERT INTO TB_EMPLOYEE (ADMISSION_DATE, BIRTH_DATE, EMAIL, NAME, TOTAL_VACATION_DAYS) VALUES (NOW(), '2020-07-14T10:00:00Z', 'test@gmail.com', 'Rafael Mariath', 22);
INSERT INTO TB_EMPLOYEE (ADMISSION_DATE, BIRTH_DATE, EMAIL, NAME, TOTAL_VACATION_DAYS) VALUES (NOW(), '2020-07-14T10:00:00Z', 'test@gmail.com', 'Caroline Schenk', 12);

INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);
INSERT INTO TB_VACATION (DATE, IS_CHECKED) VALUES (NOW(), 1);


INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (1, 1);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (1, 2);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (1, 3);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (2, 4);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (2, 5);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (2, 6);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (3, 7);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (3, 8);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (3, 9);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (4, 10);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (4, 11);
INSERT INTO TB_EMPLOYEE_VACATION(EMPLOYEE_ID, VACATION_ID) VALUES (4, 12);
